/*
 * This source file was generated by the Gradle 'init' task
 */
package io.confluent.example.aws.lambda.auditlog;

import java.util.Base64;
import java.util.Base64.Decoder;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.KafkaEvent;
import com.google.gson.Gson;
import io.confluent.examples.auditlog.ConfluentCloudAuditLogSchema;

public class LambdaConfluentAuditLogToCloudWatch implements RequestHandler<KafkaEvent, Void> {

    Gson gson = new Gson();
    public LambdaConfluentAuditLogToCloudWatch() {

    }

    @Override
    public Void handleRequest(KafkaEvent event, Context context) {
        Decoder base64Decoder = Base64.getDecoder();
        if (context != null) {
            LambdaLogger logger = context.getLogger();
            //logger.log("EVENT TYPE: " + event.getClass());
            //logger.log("EVENT: " + event.toString());
            event.getRecords().forEach((k, v) -> {
                v.forEach((record) -> {
                    //logger.log(record.getValue());
                    ConfluentCloudAuditLogSchema auditLogEvent = gson.fromJson(new String(base64Decoder.decode(record.getValue())), ConfluentCloudAuditLogSchema.class);
                    logger.log("Audit Log Event: "+auditLogEvent.toString());
                });
            });
            //logger.log(event.toString());
        } else {
            // event.getRecords().forEach((k, v) -> {
            //     v.forEach((record) -> {
            //         //logger.log(k+" IS "+v.getValue().toString());
            //         System.out.println(record.getValue());
            //         ConfluentCloudAuditLogSchema auditLogEvent = gson.fromJson(record.getValue(), Customer.class);
            //         System.out.println("Audit Log Event: "+auditLogEvent.toString());
            //     });
            // });
        }
        return null;
    }

    public static void main(String[] args) {
        //new App().handleRequest(Map.of("Lambda!", null), null);
    }
}
